const common = {
  common: { cancel: 'Cancel', save: 'Save', saving: 'Saving...', create: 'Create', notProvided: 'Not provided', loading: 'Loading...' },
  navigation: { dashboard: 'Dashboard', patients: 'Patients', calendar: 'Calendar', workspace: 'Workspace', quickAccess: 'Quick access', patientRecords: 'Patient records', signOut: 'Sign out', close: 'Close navigation', open: 'Open navigation', overlay: 'Close navigation overlay', clinicWorkspace: 'Clinic workspace', notifications: 'Notifications' },
  language: { english: 'English', vietnamese: 'Vietnamese', switch: 'Language' },
  auth: { welcome: 'Welcome back', signInDescription: 'Sign in to your clinic workspace.', username: 'Username', password: 'Password', signIn: 'Sign in', signingIn: 'Signing in...', secureAccess: 'Secure staff access', tagline: 'Care coordination, made clear.', intro: 'A calm workspace for your front desk and clinical team.', demo: 'Demo: staff@clinic.local / ChangeMe123!', unableToSignIn: 'Unable to sign in' },
  dashboard: { overview: 'Daily overview', greeting: 'Good morning, {{name}}', description: "A focused view of today's clinic activity.", openCalendar: 'Open calendar', todayAppointments: "Today's appointments", confirmed: 'Confirmed', completed: 'Completed', cancelled: 'Cancelled', acrossClinic: 'Appointments across the clinic today.', noToday: 'No appointments scheduled today.', upcoming: 'Upcoming appointments', upcomingDescription: 'Next scheduled visits requiring attention.', noUpcoming: 'No upcoming appointments.', viewCalendar: 'View full calendar', unableToLoad: 'Unable to load dashboard', loading: 'Loading dashboard...' },
  patients: { directory: 'Directory', title: 'Patients', description: 'Search, review, and maintain patient records.', add: 'Add patient', directoryTitle: 'Patient directory', total: '{{count}} total patients', search: 'Search name or phone', noFound: 'No patients found', tryAgain: 'Try another search or add a new patient.', patient: 'Patient', phone: 'Phone', dateOfBirth: 'Date of birth', gender: 'Gender', latestAppointment: 'Latest appointment', actions: 'Actions', page: 'Page {{page}} of {{pages}}', previous: 'Previous page', next: 'Next page', edit: 'Edit patient', editDetails: 'Edit details', create: 'Create patient', saveChanges: 'Save changes', formDescription: 'Keep the patient record accurate and current.', unableToLoad: 'Unable to load patients', unableToSave: 'Unable to save patient', view: 'View {{name}}' },
  patientDetail: { back: 'Back to patients', active: 'Active', record: 'Patient record {{id}}', personal: 'Personal information', contact: 'Contact and demographic details.', notes: 'Notes', notesDescription: 'Internal notes for authorized care team members.', addNote: 'Add note', note: 'Note', notePlaceholder: 'Add a note for the care team...', appointments: 'Appointment history', noAppointments: 'No appointment history.', editDescription: 'Update patient details.', unableToAddNote: 'Unable to add note', unableToLoad: 'Loading patient record...' },
  appointments: { patient: 'Patient', doctor: 'Doctor', start: 'Start time', end: 'End time', reason: 'Reason', notes: 'Notes', schedule: 'Schedule appointment', day: 'Day', week: 'Week', today: 'Today', previous: 'Previous period', next: 'Next period', inView: '{{count}} appointments in view', noAppointments: 'No appointments in this period.', noAppointmentsDescription: 'Try another period or schedule a new appointment.', endAfterStart: 'End time must be after the start time.', unableToLoad: 'Unable to load calendar', unableToCreate: 'Unable to create appointment', status: { scheduled: 'Scheduled', confirmed: 'Confirmed', completed: 'Completed', cancelled: 'Cancelled', no_show: 'No-show' } },
  errors: { requestFailed: 'Request failed', session: 'Your session has expired. Please sign in again.' },
  roles: { admin: 'Admin', doctor: 'Doctor', staff: 'Staff' },
  gender: { female: 'Female', male: 'Male', other: 'Other' },
};
export default common;