import en from '../en/common';

const common = {
  ...en,
  common: { cancel: 'Hủy', save: 'Lưu', saving: 'Đang lưu...', create: 'Tạo', notProvided: 'Chưa cung cấp', loading: 'Đang tải...' },
  navigation: { ...en.navigation, dashboard: 'Tổng quan', patients: 'Bệnh nhân', calendar: 'Lịch hẹn', workspace: 'Không gian làm việc', quickAccess: 'Truy cập nhanh', patientRecords: 'Hồ sơ bệnh nhân', signOut: 'Đăng xuất', clinicWorkspace: 'Không gian phòng khám', notifications: 'Thông báo', close: 'Đóng điều hướng', open: 'Mở điều hướng', overlay: 'Đóng lớp điều hướng' },
  language: { english: 'Tiếng Anh', vietnamese: 'Tiếng Việt', switch: 'Ngôn ngữ' },
  auth: { ...en.auth, welcome: 'Chào mừng trở lại', signInDescription: 'Đăng nhập vào không gian phòng khám.', username: 'Tên đăng nhập', password: 'Mật khẩu', signIn: 'Đăng nhập', signingIn: 'Đang đăng nhập...', secureAccess: 'Truy cập an toàn cho nhân viên', tagline: 'Điều phối chăm sóc, thật rõ ràng.', intro: 'Không gian bình tĩnh cho lễ tân và đội ngũ lâm sàng.', demo: 'Demo: staff@clinic.local / ChangeMe123!', unableToSignIn: 'Không thể đăng nhập' },
  dashboard: { ...en.dashboard, overview: 'Tổng quan trong ngày', greeting: 'Chào buổi sáng, {{name}}', description: 'Tập trung theo dõi hoạt động phòng khám hôm nay.', openCalendar: 'Mở lịch hẹn', todayAppointments: 'Lịch hẹn hôm nay', confirmed: 'Đã xác nhận', completed: 'Đã hoàn thành', cancelled: 'Đã hủy', acrossClinic: 'Các lịch hẹn trong phòng khám hôm nay.', noToday: 'Hôm nay chưa có lịch hẹn.', upcoming: 'Lịch hẹn sắp tới', upcomingDescription: 'Các lượt khám sắp tới cần được chú ý.', noUpcoming: 'Không có lịch hẹn sắp tới.', viewCalendar: 'Xem toàn bộ lịch', unableToLoad: 'Không thể tải tổng quan', loading: 'Đang tải tổng quan...' },
  patients: { ...en.patients, directory: 'Danh bạ', title: 'Bệnh nhân', description: 'Tìm kiếm, xem và quản lý hồ sơ bệnh nhân.', add: 'Thêm bệnh nhân', directoryTitle: 'Danh sách bệnh nhân', total: '{{count}} bệnh nhân', search: 'Tìm theo tên hoặc số điện thoại', noFound: 'Không tìm thấy bệnh nhân', tryAgain: 'Thử tìm kiếm khác hoặc thêm bệnh nhân mới.', patient: 'Bệnh nhân', phone: 'Điện thoại', dateOfBirth: 'Ngày sinh', gender: 'Giới tính', latestAppointment: 'Lịch hẹn gần nhất', actions: 'Thao tác', page: 'Trang {{page}} / {{pages}}', previous: 'Trang trước', next: 'Trang sau', edit: 'Chỉnh sửa bệnh nhân', editDetails: 'Sửa thông tin', create: 'Tạo bệnh nhân', saveChanges: 'Lưu thay đổi', formDescription: 'Giữ hồ sơ bệnh nhân chính xác và cập nhật.', unableToLoad: 'Không thể tải danh sách bệnh nhân', unableToSave: 'Không thể lưu bệnh nhân', view: 'Xem {{name}}' },
  patientDetail: { ...en.patientDetail, back: 'Quay lại danh sách bệnh nhân', active: 'Đang hoạt động', record: 'Hồ sơ bệnh nhân {{id}}', personal: 'Thông tin cá nhân', contact: 'Thông tin liên hệ và nhân khẩu học.', notes: 'Ghi chú', notesDescription: 'Ghi chú nội bộ dành cho đội ngũ chăm sóc được cấp quyền.', addNote: 'Thêm ghi chú', note: 'Ghi chú', notePlaceholder: 'Thêm ghi chú cho đội ngũ chăm sóc...', appointments: 'Lịch sử hẹn', noAppointments: 'Chưa có lịch sử hẹn.', editDescription: 'Cập nhật thông tin bệnh nhân.', unableToAddNote: 'Không thể thêm ghi chú', unableToLoad: 'Đang tải hồ sơ bệnh nhân...' },
  appointments: { ...en.appointments, patient: 'Bệnh nhân', doctor: 'Bác sĩ', start: 'Thời gian bắt đầu', end: 'Thời gian kết thúc', reason: 'Lý do', notes: 'Ghi chú', schedule: 'Đặt lịch hẹn', day: 'Ngày', week: 'Tuần', today: 'Hôm nay', previous: 'Kỳ trước', next: 'Kỳ sau', inView: '{{count}} lịch hẹn trong kỳ', noAppointments: 'Không có lịch hẹn trong kỳ này.', noAppointmentsDescription: 'Thử kỳ khác hoặc tạo lịch hẹn mới.', endAfterStart: 'Thời gian kết thúc phải sau thời gian bắt đầu.', unableToLoad: 'Không thể tải lịch hẹn', unableToCreate: 'Không thể tạo lịch hẹn', status: { scheduled: 'Đã lên lịch', confirmed: 'Đã xác nhận', completed: 'Đã hoàn thành', cancelled: 'Đã hủy', no_show: 'Không đến' } },
  errors: { requestFailed: 'Yêu cầu không thành công', session: 'Phiên đăng nhập đã hết hạn. Vui lòng đăng nhập lại.' },
  roles: { admin: 'Quản trị viên', doctor: 'Bác sĩ', staff: 'Nhân viên' },
  gender: { female: 'Nữ', male: 'Nam', other: 'Khác' },
};
export default common;