import { useEffect, useMemo, useState } from 'react';
import { CalendarDays, ChevronLeft, ChevronRight, Clock3, Plus } from 'lucide-react';
import { apiRequest, useAuth } from '@/lib/auth-context';
import { Button } from '@/components/ui/button';
import { Badge, Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/primitives';
import { Modal, type ModalField } from '@/components/modal';

 type Appointment = { id: string; patient_id: string; doctor_id: string; start_time: string; end_time: string; status: string; reason: string | null };
 type Patient = { id: string; full_name: string };
 type Doctor = { id: string; name: string; full_name?: string };
 const createFields = (patients: Patient[], doctors: Doctor[]): ModalField[] => [{ name: 'patient_id', label: 'Patient', type: 'select', required: true, options: patients.map((item) => ({ label: item.full_name, value: item.id })) }, { name: 'doctor_id', label: 'Doctor', type: 'select', required: true, options: doctors.map((item) => ({ label: item.name, value: item.id })) }, { name: 'start_time', label: 'Start', type: 'datetime-local', required: true }, { name: 'end_time', label: 'End', type: 'datetime-local', required: true }, { name: 'reason', label: 'Reason' }];

export function CalendarPage() {
  const { user } = useAuth(); const [date, setDate] = useState(new Date()); const [appointments, setAppointments] = useState<Appointment[]>([]); const [patients, setPatients] = useState<Patient[]>([]); const [doctors, setDoctors] = useState<Doctor[]>([]); const [open, setOpen] = useState(false); const canSchedule = user?.role === 'admin' || user?.role === 'staff';
  const dayStart = useMemo(() => { const value = new Date(date); value.setHours(0, 0, 0, 0); return value; }, [date]); const dateKey = dayStart.toISOString().slice(0, 10); const from = `${dateKey}T00:00:00.000Z`; const to = `${dateKey}T23:59:59.999Z`;
  const load = () => { apiRequest<{ appointments: Appointment[] }>(`/api/appointments?from=${encodeURIComponent(from)}&to=${encodeURIComponent(to)}`).then((result) => setAppointments(result.appointments)); };
  useEffect(() => { load(); }, [dateKey]); useEffect(() => { Promise.all([apiRequest<{ patients: Patient[] }>('/api/patients?pageSize=100'), apiRequest<{ doctors: Doctor[] }>('/api/doctors')]).then(([patientResult, doctorResult]) => { setPatients(patientResult.patients); setDoctors(doctorResult.doctors); }); }, []);
  const patientName = (id: string) => patients.find((patient) => patient.id === id)?.full_name ?? `Patient #${id.slice(0, 8)}`; const doctorName = (id: string) => doctors.find((doctor) => doctor.id === id)?.name ?? 'Doctor';
  const moveDate = (days: number) => setDate((current) => { const next = new Date(current); next.setDate(next.getDate() + days); return next; });
  const create = async (values: Record<string, string>) => { await apiRequest('/api/appointments', { method: 'POST', body: JSON.stringify({ ...values, start_time: new Date(values.start_time).toISOString(), end_time: new Date(values.end_time).toISOString() }) }); load(); };
  return <div className="space-y-6"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-medium text-primary">Planning</p><h1 className="mt-1 text-3xl font-semibold tracking-tight text-slate-900">Calendar</h1><p className="mt-2 text-sm text-muted-foreground">Keep the team and patients moving on time.</p></div>{canSchedule && <Button onClick={() => setOpen(true)}><Plus size={16} />Schedule appointment</Button>}</div><Card><CardHeader className="flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><CardTitle>{dayStart.toLocaleDateString([], { weekday: 'long', month: 'long', day: 'numeric' })}</CardTitle><CardDescription>{appointments.length} appointment{appointments.length === 1 ? '' : 's'} scheduled</CardDescription></div><div className="flex items-center gap-1"><Button variant="outline" size="icon" onClick={() => moveDate(-1)} aria-label="Previous day"><ChevronLeft size={17} /></Button><Button variant="outline" size="sm" onClick={() => setDate(new Date())}>Today</Button><Button variant="outline" size="icon" onClick={() => moveDate(1)} aria-label="Next day"><ChevronRight size={17} /></Button></div></CardHeader><CardContent>{appointments.length === 0 ? <div className="flex min-h-72 flex-col items-center justify-center rounded-md border border-dashed bg-slate-50 text-center"><CalendarDays className="text-muted-foreground" size={28} /><p className="mt-3 font-medium">A clear schedule</p><p className="mt-1 text-sm text-muted-foreground">There are no appointments on this day.</p></div> : <div className="space-y-3">{appointments.map((appointment) => <AppointmentRow key={appointment.id} appointment={appointment} patientName={patientName(appointment.patient_id)} doctorName={doctorName(appointment.doctor_id)} onStatusChange={async (status) => { await apiRequest(`/api/appointments/${appointment.id}`, { method: 'PATCH', body: JSON.stringify({ status }) }); load(); }} />)}</div>}</CardContent></Card><Modal open={open} onOpenChange={setOpen} title="Schedule appointment" description="Appointments are checked for doctor time conflicts." fields={createFields(patients, doctors)} onSubmit={create} submitLabel="Schedule" /></div>;
}

function AppointmentRow({ appointment, patientName, doctorName, onStatusChange }: { appointment: Appointment; patientName: string; doctorName: string; onStatusChange: (status: string) => Promise<void> }) { const statusVariant = appointment.status === 'completed' ? 'success' : appointment.status === 'cancelled' ? 'danger' : appointment.status === 'no_show' ? 'warning' : 'default'; return <div className="flex flex-col gap-4 rounded-lg border p-4 sm:flex-row sm:items-center"><div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-md bg-primary/10 text-primary"><Clock3 size={20} /></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="font-medium text-slate-900">{patientName}</p><Badge variant={statusVariant}>{appointment.status.replace('_', ' ')}</Badge></div><p className="mt-1 text-sm text-muted-foreground">{new Date(appointment.start_time).toLocaleTimeString([], { hour: 'numeric', minute: '2-digit' })} - {new Date(appointment.end_time).toLocaleTimeString([], { hour: 'numeric', minute: '2-digit' })} · {doctorName}</p><p className="mt-1 text-xs text-muted-foreground">{appointment.reason ?? 'Routine visit'}</p></div>{appointment.status === 'scheduled' && <div className="flex gap-2"><Button variant="outline" size="sm" onClick={() => onStatusChange('completed')}>Complete</Button><Button variant="ghost" size="sm" onClick={() => onStatusChange('cancelled')}>Cancel</Button></div>}</div>; }
