import { useEffect, useState } from 'react';
import { ArrowRight, CalendarCheck2, CheckCircle2, Clock3, XCircle } from 'lucide-react';
import { Link } from 'react-router-dom';
import { apiRequest, useAuth } from '@/lib/auth-context';
import { Badge, Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/primitives';
import { Button } from '@/components/ui/button';

type Appointment = { id: string; patient_id: string; doctor_id: string; start_at: string; end_at: string; status: string; reason: string | null };
type Dashboard = { summary: { today: number; confirmed: number; completed: number; cancelled: number }; today: Appointment[]; upcoming: Appointment[] };
const statusVariant = (status: string) => status === 'completed' ? 'success' as const : status === 'cancelled' ? 'danger' as const : status === 'no_show' ? 'warning' as const : 'default' as const;

export function DashboardPageV2() {
  const { user } = useAuth(); const [data, setData] = useState<Dashboard | null>(null); const [patients, setPatients] = useState<Record<string, string>>({}); const [error, setError] = useState('');
  useEffect(() => { Promise.all([apiRequest<Dashboard>('/api/dashboard'), apiRequest<{ patients: { id: string; full_name: string }[] }>('/api/patients?pageSize=100')]).then(([dashboard, patientResult]) => { setData(dashboard); setPatients(Object.fromEntries(patientResult.patients.map((patient) => [patient.id, patient.full_name]))); }).catch((err) => setError(err instanceof Error ? err.message : 'Unable to load dashboard')); }, []);
  if (error) return <p className="rounded-md bg-red-50 p-4 text-sm text-red-700">{error}</p>;
  if (!data) return <p className="py-12 text-center text-sm text-muted-foreground">Loading dashboard...</p>;
  const stats = [{ label: "Today's appointments", value: data.summary.today, icon: CalendarCheck2 }, { label: 'Confirmed', value: data.summary.confirmed, icon: Clock3 }, { label: 'Completed', value: data.summary.completed, icon: CheckCircle2 }, { label: 'Cancelled', value: data.summary.cancelled, icon: XCircle }];
  return <div className="space-y-8"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-medium text-primary">Daily overview</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">Good morning, {user?.full_name.split(' ')[0]}</h1><p className="mt-2 text-sm text-muted-foreground">A focused view of today’s clinic activity.</p></div><Button asChild={false} onClick={() => window.location.assign('/calendar')}>Open calendar <ArrowRight size={16} /></Button></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{stats.map(({ label, value, icon: Icon }) => <Card key={label}><CardContent className="flex items-center justify-between p-5"><div><p className="text-sm text-muted-foreground">{label}</p><p className="mt-2 text-3xl font-semibold">{value}</p></div><Icon className="text-primary" size={22} /></CardContent></Card>)}</div><div className="grid gap-6 xl:grid-cols-[1.2fr_1fr]"><Card><CardHeader><CardTitle>Today's appointments</CardTitle><CardDescription>Appointments across the clinic today.</CardDescription></CardHeader><CardContent className="space-y-3">{data.today.length === 0 ? <p className="rounded-md bg-slate-50 p-8 text-center text-sm text-muted-foreground">No appointments scheduled today.</p> : data.today.map((appointment) => <AppointmentLine key={appointment.id} appointment={appointment} patientName={patients[appointment.patient_id] ?? 'Patient'} />)}</CardContent></Card><Card><CardHeader><CardTitle>Upcoming appointments</CardTitle><CardDescription>Next scheduled visits requiring attention.</CardDescription></CardHeader><CardContent className="space-y-3">{data.upcoming.map((appointment) => <AppointmentLine key={appointment.id} appointment={appointment} patientName={patients[appointment.patient_id] ?? 'Patient'} />)}{data.upcoming.length === 0 && <p className="text-sm text-muted-foreground">No upcoming appointments.</p>}<Link to="/calendar" className="inline-flex items-center gap-2 pt-2 text-sm font-medium text-primary">View full calendar <ArrowRight size={15} /></Link></CardContent></Card></div></div>;
}
function AppointmentLine({ appointment, patientName }: { appointment: Appointment; patientName: string }) { return <div className="flex items-center justify-between gap-3 border-b pb-3 last:border-0 last:pb-0"><div><p className="font-medium">{patientName}</p><p className="text-sm text-muted-foreground">{new Date(appointment.start_at).toLocaleString([], { weekday: 'short', hour: 'numeric', minute: '2-digit' })}</p></div><Badge variant={statusVariant(appointment.status)}>{appointment.status.replace('_', ' ')}</Badge></div>; }
