import { useEffect, useState } from 'react';
import { ArrowRight, CalendarCheck2, CheckCircle2, Clock3, XCircle } from 'lucide-react';
import { Link } from 'react-router-dom';
import { apiRequest, useAuth } from '@/lib/auth-context';
import { Badge, Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/primitives';
import { Button } from '@/components/ui/button';
import { useTranslation } from 'react-i18next';
import { formatDateTime } from '@/lib/utils';

type Appointment = { id: string; patient_id: string; doctor_id: string; start_at: string; end_at: string; status: string; reason: string | null };
type Dashboard = { summary: { today: number; confirmed: number; completed: number; cancelled: number }; today: Appointment[]; upcoming: Appointment[] };
const statusVariant = (status: string) => status === 'completed' ? 'success' as const : status === 'cancelled' ? 'danger' as const : status === 'no_show' ? 'warning' as const : 'default' as const;

export function DashboardPageV2() {
  const { user } = useAuth(); const { t } = useTranslation(); const [data, setData] = useState<Dashboard | null>(null); const [patients, setPatients] = useState<Record<string, string>>({}); const [error, setError] = useState('');
  useEffect(() => { Promise.all([apiRequest<Dashboard>('/api/dashboard'), apiRequest<{ patients: { id: string; full_name: string }[] }>('/api/patients?pageSize=100')]).then(([dashboard, patientResult]) => { setData(dashboard); setPatients(Object.fromEntries(patientResult.patients.map((patient) => [patient.id, patient.full_name]))); }).catch((err) => setError(err instanceof Error ? err.message : t('dashboard.unableToLoad'))); }, [t]);
  if (error) return <p className="rounded-md bg-red-50 p-4 text-sm text-red-700">{error}</p>;
  if (!data) return <p className="py-12 text-center text-sm text-muted-foreground">{t('dashboard.loading')}</p>;
  const stats = [{ label: t('dashboard.todayAppointments'), value: data.summary.today, icon: CalendarCheck2 }, { label: t('dashboard.confirmed'), value: data.summary.confirmed, icon: Clock3 }, { label: t('dashboard.completed'), value: data.summary.completed, icon: CheckCircle2 }, { label: t('dashboard.cancelled'), value: data.summary.cancelled, icon: XCircle }];
  return <div className="space-y-8"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-medium text-primary">{t('dashboard.overview')}</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">{t('dashboard.greeting', { name: user?.full_name.split(' ')[0] })}</h1><p className="mt-2 text-sm text-muted-foreground">{t('dashboard.description')}</p></div><Button asChild={false} onClick={() => window.location.assign('/calendar')}>{t('dashboard.openCalendar')} <ArrowRight size={16} /></Button></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{stats.map(({ label, value, icon: Icon }) => <Card key={label}><CardContent className="flex items-center justify-between p-5"><div><p className="text-sm text-muted-foreground">{label}</p><p className="mt-2 text-3xl font-semibold">{value}</p></div><Icon className="text-primary" size={22} /></CardContent></Card>)}</div><div className="grid gap-6 xl:grid-cols-[1.2fr_1fr]"><Card><CardHeader><CardTitle>{t('dashboard.todayAppointments')}</CardTitle><CardDescription>{t('dashboard.acrossClinic')}</CardDescription></CardHeader><CardContent className="space-y-3">{data.today.length === 0 ? <p className="rounded-md bg-slate-50 p-8 text-center text-sm text-muted-foreground">{t('dashboard.noToday')}</p> : data.today.map((appointment) => <AppointmentLine key={appointment.id} appointment={appointment} patientName={patients[appointment.patient_id] ?? t('patients.patient')} />)}</CardContent></Card><Card><CardHeader><CardTitle>{t('dashboard.upcoming')}</CardTitle><CardDescription>{t('dashboard.upcomingDescription')}</CardDescription></CardHeader><CardContent className="space-y-3">{data.upcoming.map((appointment) => <AppointmentLine key={appointment.id} appointment={appointment} patientName={patients[appointment.patient_id] ?? t('patients.patient')} />)}{data.upcoming.length === 0 && <p className="text-sm text-muted-foreground">{t('dashboard.noUpcoming')}</p>}<Link to="/calendar" className="inline-flex items-center gap-2 pt-2 text-sm font-medium text-primary">{t('dashboard.viewCalendar')} <ArrowRight size={15} /></Link></CardContent></Card></div></div>;
}
function AppointmentLine({ appointment, patientName }: { appointment: Appointment; patientName: string }) { const { t } = useTranslation(); return <div className="flex items-center justify-between gap-3 border-b pb-3 last:border-0 last:pb-0"><div><p className="font-medium">{patientName}</p><p className="text-sm text-muted-foreground">{formatDateTime(appointment.start_at)}</p></div><Badge variant={statusVariant(appointment.status)}>{t(`appointments.status.${appointment.status}`, { defaultValue: appointment.status.replace('_', ' ') })}</Badge></div>; }
