import { ArrowRight, Baby, Check, ChevronDown, Clock3, HeartPulse, ShieldCheck, Sparkles, UsersRound } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import { usePageMeta } from '@/lib/seo';

const icons = [HeartPulse, Sparkles, Sparkles, ShieldCheck, UsersRound, Baby];
const benefitIcons = [ShieldCheck, HeartPulse, Clock3, UsersRound];

export function LandingPage() {
  const { t } = useTranslation();
  const services = t('public.services.items', { returnObjects: true }) as Array<{ slug: string; title: string; description: string }>;
  const benefits = t('public.benefits.items', { returnObjects: true }) as Array<{ title: string; description: string }>;
  const doctors = t('public.doctors.items', { returnObjects: true }) as Array<{ name: string; specialty: string; description: string }>;
  const faq = t('public.faq.items', { returnObjects: true }) as Array<{ question: string; answer: string }>;
  const testimonials = t('public.testimonials.items', { returnObjects: true }) as Array<{ quote: string; name: string }>;
  usePageMeta({
    title: t('phase9.meta.homeTitle'),
    description: t('phase9.meta.homeDescription'),
  });

  return <main id="top">
    <section className="relative overflow-hidden bg-[#e5f0ec]"><div className="mx-auto grid max-w-7xl items-center gap-10 px-5 pb-20 pt-12 lg:grid-cols-[1.05fr_0.95fr] lg:px-8 lg:pb-28 lg:pt-20"><div><p className="public-kicker mb-5 flex items-center gap-2"><span className="h-px w-8 bg-[#f0b936]" />{t('public.hero.eyebrow')}</p><h1 className="max-w-2xl font-serif text-5xl leading-[1.02] tracking-tight sm:text-6xl lg:text-7xl">{t('public.hero.title')}</h1><p className="mt-6 max-w-xl text-lg leading-8 text-[#52716e]">{t('public.hero.description')}</p><div className="mt-8 flex flex-wrap gap-3"><a href="/book" className="public-button bg-[#12343b] text-white">{t('public.bookAppointment')}<ArrowRight size={16} /></a><a href="#services" className="public-button border border-[#9ab8b0] text-[#12343b]">{t('public.hero.viewServices')}</a></div><p className="mt-10 text-sm text-[#52716e]">{t('public.hero.comfortNote')}</p></div><div className="relative mx-auto w-full max-w-md lg:max-w-none"><div className="relative overflow-hidden rounded-[2rem] rounded-bl-[7rem] border-[12px] border-white bg-[#c5ddd5] shadow-2xl"><img src="https://images.unsplash.com/photo-1606811971618-4486d14f3f99?auto=format&fit=crop&w=900&q=80" alt={t('public.hero.imageAlt')} className="aspect-[4/5] w-full object-cover" fetchPriority="high" width={900} height={1125} sizes="(min-width: 1024px) 44vw, (min-width: 640px) 70vw, 92vw" /></div><div className="absolute -bottom-5 -left-5 flex items-center gap-3 rounded-2xl bg-white px-4 py-3 shadow-xl"><Sparkles size={19} className="text-[#b77d00]" /><span className="text-xs font-bold">{t('public.hero.card')}</span></div></div></div></section>
    <div className="border-b border-[#dce9e5] bg-white"><div className="mx-auto grid max-w-7xl gap-6 px-5 py-7 sm:grid-cols-2 lg:grid-cols-4 lg:px-8">{benefits.map((item, index) => { const Icon = benefitIcons[index]; return <article key={item.title} className="flex gap-3"><Icon className="mt-0.5 shrink-0 text-[#c18b13]" size={21} /><div><h2 className="text-sm font-bold">{item.title}</h2><p className="mt-1 text-xs leading-5 text-[#66817e]">{item.description}</p></div></article>; })}</div></div>
    <section id="services" className="mx-auto max-w-7xl px-5 py-20 lg:px-8 lg:py-28"><div className="mb-10"><p className="public-kicker">{t('public.services.eyebrow')}</p><h2 className="public-heading">{t('public.services.title')}</h2></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{services.map((service, index) => { const Icon = icons[index]; return <article key={service.slug} className="group border border-[#dce9e5] bg-white p-6 transition hover:-translate-y-1 hover:shadow-lg"><div className="mb-10 flex h-11 w-11 items-center justify-center rounded-xl bg-[#e5f0ec] text-[#24636a]"><Icon size={21} /></div><h3 className="font-serif text-2xl">{service.title}</h3><p className="mt-2 min-h-12 text-sm leading-6 text-[#66817e]">{service.description}</p><Link to={`/services/${service.slug}`} className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-[#24636a]">{t('public.learnMore')}<ArrowRight size={15} /></Link></article>; })}</div></section>
    <section id="about" className="bg-[#f0f6f3]"><div className="mx-auto grid max-w-7xl items-center gap-12 px-5 py-20 lg:grid-cols-2 lg:px-8 lg:py-28"><div className="overflow-hidden rounded-[2rem] rounded-tr-[7rem] bg-[#c5ddd5]"><img src="https://images.unsplash.com/photo-1629909613654-28e377c37b09?auto=format&fit=crop&w=900&q=80" alt={t('public.about.imageAlt')} className="aspect-[5/4] w-full object-cover" loading="lazy" width={900} height={720} sizes="(min-width: 1024px) 44vw, (min-width: 640px) 70vw, 92vw" /></div><div><p className="public-kicker">{t('public.about.eyebrow')}</p><h2 className="public-heading">{t('public.about.title')}</h2><p className="mt-5 text-base leading-8 text-[#52716e]">{t('public.about.description')}</p><a href="/about" className="public-button mt-7 bg-[#12343b] text-white">{t('public.about.cta')}<ArrowRight size={16} /></a></div></div></section>
    <section id="doctors" className="mx-auto max-w-7xl px-5 py-20 lg:px-8 lg:py-28"><p className="public-kicker">{t('public.doctors.eyebrow')}</p><h2 className="public-heading mb-10">{t('public.doctors.title')}</h2><div className="grid gap-5 md:grid-cols-3">{doctors.map((doctor, index) => <article key={doctor.name} className="border border-[#dce9e5] bg-white"><div className={`flex aspect-[4/3] items-end justify-center ${['bg-[#d9e8df]', 'bg-[#e8dfd5]', 'bg-[#d9e0e8]'][index]}`}><div className="flex h-32 w-32 translate-y-6 items-center justify-center rounded-full border-8 border-white bg-[#f4c95d] font-serif text-5xl">{doctor.name.charAt(0)}</div></div><div className="p-7 pt-12"><h3 className="font-serif text-2xl">{doctor.name}</h3><p className="mt-1 text-sm font-bold text-[#c18b13]">{doctor.specialty}</p><p className="mt-4 text-sm leading-6 text-[#66817e]">{doctor.description}</p></div></article>)}</div></section>
    <section className="bg-[#12343b] text-white"><div className="mx-auto grid max-w-7xl gap-12 px-5 py-20 lg:grid-cols-2 lg:px-8"><div><p className="public-kicker text-[#f4c95d]">{t('public.why.eyebrow')}</p><h2 className="public-heading text-white">{t('public.why.title')}</h2><div className="mt-8 space-y-5">{(t('public.why.items', { returnObjects: true }) as string[]).map((item) => <p key={item} className="flex gap-3 text-sm leading-6 text-[#b8cfca]"><Check className="mt-1 shrink-0 text-[#f4c95d]" size={18} />{item}</p>)}</div></div><div id="faq"><p className="public-kicker text-[#f4c95d]">{t('public.faq.eyebrow')}</p><h2 className="font-serif text-3xl">{t('public.faq.title')}</h2><div className="mt-6 divide-y divide-[#31535a]">{faq.map((item) => <details key={item.question} className="group py-4"><summary className="flex cursor-pointer list-none items-center justify-between gap-4 text-sm font-bold focus-visible:outline focus-visible:outline-2 focus-visible:outline-[#f4c95d]"><span>{item.question}</span><ChevronDown className="shrink-0 transition group-open:rotate-180" size={17} /></summary><p className="mt-3 text-sm leading-6 text-[#b8cfca]">{item.answer}</p></details>)}</div></div></div></section>
    <section className="bg-[#f4c95d]"><div className="mx-auto flex max-w-7xl flex-col gap-6 px-5 py-14 sm:flex-row sm:items-center sm:justify-between lg:px-8"><div><h2 className="font-serif text-4xl">{t('public.cta.title')}</h2><p className="mt-2 text-sm text-[#456460]">{t('public.cta.description')}</p></div><a href="/book" className="public-button shrink-0 bg-[#12343b] text-white">{t('public.bookAppointment')}<ArrowRight size={16} /></a></div></section>
    <section className="mx-auto max-w-7xl px-5 py-20 lg:px-8"><div className="grid gap-5 md:grid-cols-3">{testimonials.map((item) => <figure key={item.name} className="border-l-2 border-[#f4c95d] pl-5"><blockquote className="font-serif text-xl leading-8">“{item.quote}”</blockquote><figcaption className="mt-4 text-xs font-bold uppercase tracking-wider text-[#66817e]">{item.name} · {t('public.testimonials.placeholder')}</figcaption></figure>)}</div></section>
  </main>;
}