import { Baby, ChevronDown, HeartPulse, MapPin, ShieldCheck, Smile, Sparkles, Sun } from 'lucide-react';
import { useEffect } from 'react';
import { Link, useParams } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import { doctorRecords, faqKeys, serviceRecords } from '@/data/public-data';

const iconMap = { heart: HeartPulse, sparkles: Sparkles, sun: Sun, shield: ShieldCheck, smile: Smile, baby: Baby };

type Translator = (key: string, options?: Record<string, unknown>) => string;
function useMeta(title: string, description: string) { useEffect(() => { document.title = title; const tag = document.querySelector('meta[name="description"]') ?? document.createElement('meta'); tag.setAttribute('name', 'description'); tag.setAttribute('content', description); document.head.appendChild(tag); }, [title, description]); }
function PageIntro({ eyebrow, title, intro }: { eyebrow: string; title: string; intro: string }) { return <section className="bg-[#e5f0ec] px-5 py-16 lg:px-8 lg:py-24"><div className="mx-auto max-w-7xl"><p className="public-kicker">{eyebrow}</p><h1 className="public-heading max-w-3xl">{title}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-[#52716e]">{intro}</p></div></section>; }
function Crumbs({ current, parent = 'services' }: { current: string; parent?: 'services' | 'doctors' }) { const { t } = useTranslation('common'); return <nav aria-label={t('publicPages.breadcrumbs.home')} className="mx-auto max-w-7xl px-5 pt-7 text-sm text-[#66817e] lg:px-8"><Link to="/" className="hover:text-[#12343b]">{t('publicPages.breadcrumbs.home')}</Link><span className="px-2">/</span><Link to={`/${parent}`} className="hover:text-[#12343b]">{t(`publicPages.breadcrumbs.${parent}`)}</Link><span className="px-2">/</span><span className="text-[#12343b]">{current}</span></nav>; }
function BookButton() { const { t } = useTranslation('common'); return <Link to="/book" className="public-button bg-[#12343b] text-white">{t('publicPages.common.book')}</Link>; }
function NotFound() { const { t } = useTranslation('common'); return <main className="mx-auto max-w-3xl px-5 py-24 text-center lg:px-8"><h1 className="public-heading mx-auto">{t('publicPages.common.notFoundTitle')}</h1><p className="mt-5 text-[#66817e]">{t('publicPages.common.notFoundDescription')}</p><Link to="/" className="public-button mt-8 bg-[#12343b] text-white">{t('publicPages.common.backHome')}</Link></main>; }

export function ServicesPage() { const { t } = useTranslation('common'); useMeta(t('publicPages.meta.services'), t('publicPages.meta.description')); return <><PageIntro eyebrow={t('public.nav.services')} title={t('publicPages.services.title')} intro={t('publicPages.services.intro')} /><section className="mx-auto max-w-7xl px-5 py-16 lg:px-8 lg:py-24"><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{serviceRecords.map((record) => { const Icon = iconMap[record.icon]; return <article key={record.slug} className="border border-[#dce9e5] bg-white p-7"><div className="mb-10 flex h-12 w-12 items-center justify-center rounded-xl bg-[#e5f0ec] text-[#24636a]"><Icon size={23} /></div><h2 className="font-serif text-2xl">{t(`publicPages.services.items.${record.slug}.title`)}</h2><p className="mt-3 min-h-12 text-sm leading-6 text-[#66817e]">{t(`publicPages.services.items.${record.slug}.short`)}</p><Link to={`/services/${record.slug}`} className="mt-6 inline-flex font-bold text-[#24636a]">{t('public.learnMore')} <span className="pl-2">→</span></Link></article>; })}</div></section></>; }
export function ServiceDetailPage() { const { slug } = useParams(); const { t } = useTranslation('common'); const record = serviceRecords.find((item) => item.slug === slug); const title = record ? t(`publicPages.services.items.${record.slug}.title`) : t('publicPages.common.notFoundTitle'); useMeta(title, t('publicPages.meta.description')); if (!record) return <NotFound />; const benefits = t(`publicPages.services.items.${record.slug}.benefits`, { returnObjects: true }) as string[]; return <><Crumbs current={title} /><main className="mx-auto max-w-7xl px-5 py-14 lg:px-8 lg:py-20"><div className="max-w-3xl"><p className="public-kicker">{t('public.nav.services')}</p><h1 className="public-heading">{title}</h1><p className="mt-6 text-xl leading-8 text-[#52716e]">{t('publicPages.services.detailIntro')}</p><p className="mt-8 text-base leading-8 text-[#52716e]">{t(`publicPages.services.items.${record.slug}.detail`)}</p><h2 className="mt-12 font-serif text-3xl">{t('publicPages.services.benefits')}</h2><ul className="mt-5 grid gap-3 sm:grid-cols-3">{benefits.map((benefit) => <li key={benefit} className="border-l-2 border-[#f4c95d] pl-4 text-sm leading-6">{benefit}</li>)}</ul><div className="mt-12"><BookButton /></div></div></main></>; }
export function AboutPage() { const { t } = useTranslation('common'); useMeta(t('publicPages.meta.about'), t('publicPages.meta.description')); const values = t('publicPages.about.values', { returnObjects: true }) as Array<{ title: string; text: string }>; return <><PageIntro eyebrow={t('publicPages.about.eyebrow')} title={t('publicPages.about.title')} intro={t('publicPages.about.intro')} /><main className="mx-auto max-w-7xl px-5 py-16 lg:px-8 lg:py-24"><div className="grid gap-12 lg:grid-cols-[0.8fr_1.2fr]"><div><h2 className="font-serif text-3xl">{t('publicPages.about.missionTitle')}</h2><p className="mt-4 leading-8 text-[#52716e]">{t('publicPages.about.mission')}</p></div><div><h2 className="font-serif text-3xl">{t('publicPages.about.valuesTitle')}</h2><div className="mt-6 grid gap-5 sm:grid-cols-3">{values.map((value) => <article key={value.title} className="border-t-2 border-[#f4c95d] pt-4"><h3 className="font-bold">{value.title}</h3><p className="mt-2 text-sm leading-6 text-[#66817e]">{value.text}</p></article>)}</div></div></div><div className="mt-16 bg-[#f0f6f3] p-8 lg:p-12"><h2 className="font-serif text-3xl">{t('publicPages.about.environmentTitle')}</h2><p className="mt-4 max-w-2xl leading-8 text-[#52716e]">{t('publicPages.about.environment')}</p><div className="mt-7"><BookButton /></div></div></main></>; }
export function DoctorsPage() { const { t } = useTranslation('common'); useMeta(t('publicPages.meta.doctors'), t('publicPages.meta.description')); return <><PageIntro eyebrow={t('public.nav.doctors')} title={t('publicPages.doctors.title')} intro={t('publicPages.doctors.intro')} /><section className="mx-auto max-w-7xl px-5 py-16 lg:px-8 lg:py-24"><div className="grid gap-5 md:grid-cols-3">{doctorRecords.map((record) => <article key={record.slug} className="border border-[#dce9e5] bg-white"><div className={`flex aspect-[4/3] items-end justify-center ${record.tone}`}><div className="flex h-32 w-32 translate-y-6 items-center justify-center rounded-full border-8 border-white bg-[#f4c95d] font-serif text-4xl">{record.initials}</div></div><div className="p-7 pt-12"><h2 className="font-serif text-2xl">{t(`publicPages.doctors.items.${record.slug}.name`)}</h2><p className="mt-1 text-sm font-bold text-[#c18b13]">{t(`publicPages.doctors.items.${record.slug}.specialty`)}</p><p className="mt-4 text-sm leading-6 text-[#66817e]">{t(`publicPages.doctors.items.${record.slug}.bio`)}</p><Link to={`/doctors/${record.slug}`} className="mt-5 inline-flex font-bold text-[#24636a]">{t('public.learnMore')} <span className="pl-2">→</span></Link></div></article>)}</div></section></>; }
export function DoctorDetailPage() { const { slug } = useParams(); const { t } = useTranslation('common'); const record = doctorRecords.find((item) => item.slug === slug); const name = record ? t(`publicPages.doctors.items.${record.slug}.name`) : t('publicPages.common.notFoundTitle'); useMeta(name, t('publicPages.meta.description')); if (!record) return <NotFound />; const areas = t(`publicPages.doctors.items.${record.slug}.areas`, { returnObjects: true }) as string[]; return <><Crumbs parent="doctors" current={name} /><main className="mx-auto grid max-w-7xl gap-12 px-5 py-14 lg:grid-cols-[0.7fr_1.3fr] lg:px-8 lg:py-20"><div className={`flex aspect-square max-w-sm items-end justify-center ${record.tone}`}><div className="mb-10 flex h-36 w-36 items-center justify-center rounded-full border-8 border-white bg-[#f4c95d] font-serif text-5xl">{record.initials}</div></div><div><p className="public-kicker">{t(`publicPages.doctors.items.${record.slug}.specialty`)}</p><h1 className="public-heading">{name}</h1><p className="mt-6 text-lg leading-8 text-[#52716e]">{t(`publicPages.doctors.items.${record.slug}.bio`)}</p><h2 className="mt-10 font-serif text-3xl">{t('publicPages.doctors.practice')}</h2><ul className="mt-4 grid gap-3 sm:grid-cols-3">{areas.map((area) => <li key={area} className="border-l-2 border-[#f4c95d] pl-3 text-sm">{area}</li>)}</ul><div className="mt-10"><BookButton /></div></div></main></>; }
export function FaqPage() { const { t } = useTranslation('common'); useMeta(t('publicPages.meta.faq'), t('publicPages.meta.description')); return <><PageIntro eyebrow={t('public.nav.faq')} title={t('publicPages.faq.title')} intro={t('publicPages.faq.intro')} /><main className="mx-auto max-w-4xl px-5 py-16 lg:px-8 lg:py-24"><div className="divide-y divide-[#dce9e5] border-y border-[#dce9e5]">{faqKeys.map((key) => <details key={key} className="group py-5"><summary className="flex cursor-pointer list-none items-center justify-between gap-5 text-base font-bold focus-visible:outline focus-visible:outline-2 focus-visible:outline-[#c18b13]"><span>{t(`publicPages.faq.items.${key}.0`)}</span><ChevronDown className="shrink-0 transition group-open:rotate-180" size={19} /></summary><p className="mt-4 max-w-3xl text-sm leading-7 text-[#66817e]">{t(`publicPages.faq.items.${key}.1`)}</p></details>)}</div></main></>; }
export function ContactPage() { const { t } = useTranslation('common'); useMeta(t('publicPages.meta.contact'), t('publicPages.meta.description')); return <><PageIntro eyebrow={t('public.nav.contact')} title={t('publicPages.contact.title')} intro={t('publicPages.contact.intro')} /><main className="mx-auto grid max-w-7xl gap-10 px-5 py-16 lg:grid-cols-2 lg:px-8 lg:py-24"><section className="space-y-8"><h2 className="font-serif text-3xl">{t('publicPages.contact.clinic')}</h2>{(['address', 'phone', 'email', 'hours'] as const).map((key) => <div key={key}><h3 className="text-xs font-bold uppercase tracking-[0.16em] text-[#c18b13]">{t(`publicPages.contact.${key}Label`)}</h3><p className="mt-2 text-[#52716e]">{t(`publicPages.contact.${key}`)}</p></div>)}<BookButton /></section><section className="flex min-h-80 flex-col items-center justify-center border border-[#b8cfca] bg-[#e5f0ec] p-8 text-center"><MapPin className="text-[#24636a]" size={32} /><h2 className="mt-4 font-serif text-2xl">{t('publicPages.contact.mapTitle')}</h2><p className="mt-3 max-w-sm text-sm leading-6 text-[#52716e]">{t('publicPages.contact.mapText')}</p><a className="mt-5 font-bold text-[#24636a] underline" href="https://maps.google.com" target="_blank" rel="noreferrer">{t('publicPages.contact.mapLink')}</a></section></main></>; }
